# Generated by Django 5.1.6 on 2025-10-22 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='projects/thumbnails/')),
                ('short_description', models.CharField(help_text='The short summary shown on the portfolio grid.', max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('technologies_used', models.CharField(blank=True, help_text='e.g., HTML, CSS, Django, Photoshop', max_length=200)),
                ('detailed_description', models.TextField(blank=True, help_text='The full case study/review for the project detail page.')),
                ('project_link', models.URLField(blank=True, help_text='The URL to the live site or GitHub repo.')),
                ('main_image', models.ImageField(blank=True, help_text='A large banner image for the detail page.', null=True, upload_to='projects/main_images/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.category')),
            ],
            options={
                'ordering': ['-date_completed'],
            },
        ),
    ]
